version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/toddy_shop_backend"
    schedule:
      interval: "weekly"
    groups:
      backend-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/toddy_shop_frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-deps:
        patterns:
          - "*"
